### ISSUE TITLE
Mention Vortex and explain Community and Unofficial patch difference

### ISSUE THREAD

**Issue by the-holographic** [ejams1/starfield-modding-guide#5]
Since this is public, variability is needed. For example, fixing Vortex load order upon Shattered Space release with Starfield.ccc was much quicker than waiting for a dll patch from MO2.

MO2 has no collection support and does not open Nexus links.

the patch issue speaks for itself.

**Comment by ejams1** [comment]
I don't use Vortex so I'm not sure what is involved there. If you have links or info on these issues I'd be happy to look into it and look at including info about it but I don't plan on using it myself so support may be limited there.

To address your other points:

- MO2 definitely opens Nexus links, I use it all the time while building my own list
- MO2 + stock game folder layout preserves the game version such that even if an update is released, it won't auto-update and break your list
- Support may have lagged previously but from what I have experienced with the latest dev build, MO2 seems to support all the DLC correctly and I have had no issues
- Collections are a native feature of Vortex but the MO2 equivalent is wabbajack which I have more experience with

Note that I am using the latest 2.5.3 dev 2 build of MO2 as outlined in the doc as Starfield support is ongoing development but at this stage it seems stable enough.

**Comment by ejams1** [comment]
All that is to say - I welcome contributions from others regarding topics I myself am not as familiar with, so if you or anyone else has more experience with vortex and related issues/fixes, please open a PR and I'd be happy to review!

**Comment by ejams1** [comment]
I didn't notice the other part of the title - "mention the difference between the unofficial and community patches". Will address that to the best of my knowledge.
